

server:
  port: 8080

spring:
  datasource:
    password: a12345
    username: huifer
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.225.144:3306/scrum?useUnicode=true&characterEncoding=utf8&useSSL=false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: localhost
    port: 32768
    max-active: 4
    max-wait: -1
    max-idle: 4
    min-idle: 0
    timeout: 20s


mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.example.webdemo.entity

mybatis-plus:
  type-aliases-package: com.example.webdemo.entity