server:
  port: 8080

spring:
  datasource:
    password: shandsuc3
    username: shandsuc3
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.0.124:3306/shandsuc3?useUnicode=true&characterEncoding=utf8&useSSL=false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 3
    host: localhost
    port: 6379
    max-active: 4
    max-wait: -1
    max-idle: 4
    min-idle: 0
    timeout: 20s


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.example.webdemo.entity

mybatis-plus:
  type-aliases-package: com.example.webdemo.entity